//! IPC message types and protocol for GUI ↔ Daemon communication.
//!
//! Provides the [`IpcMessage`] enum that carries all requests from the GUI
//! client to the daemon and all responses back. Messages are serialized
//! as JSON, one per line (newline-delimited frames).
//!
//! The `#[serde(tag = "type")]` attribute enables envelope-style
//! discrimination so the receiver can match responses to requests.

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Message types — Client → Daemon
// ---------------------------------------------------------------------------

/// Requests sent from the Tauri GUI client to the daemon.
///
/// Each variant carries the parameters needed to execute the operation.
///
/// ## Protocol Notes
///
/// - Messages are JSON-encoded with a trailing newline.
/// - The `type` field (enforced by `serde(tag = "type")`) is used to
///   discriminate the variant.
/// - The daemon responds with a matching `IpcMessage` response variant.
/// - `request_id` is an optional correlation ID echoed back in responses.

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum IpcRequest {
    /// Update daemon configuration.
    SetConfig {
        config: serde_json::Value,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        request_id: Option<String>,
    },

    /// Ask the daemon to reload configuration from disk.
    ReloadConfig {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        request_id: Option<String>,
    },

    /// Test whether a shortcut can be processed.
    TestShortcut {
        keys: Vec<String>,
        action: serde_json::Value,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        request_id: Option<String>,
    },

    /// Query current daemon status.
    GetStatus {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        request_id: Option<String>,
    },

    /// Start the daemon (if not running).
    StartDaemon {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        request_id: Option<String>,
    },

    /// Stop the daemon (if running).
    StopDaemon {
        #[serde(default, skip_serializing_if = "Option::is_none")]
        request_id: Option<String>,
    },
}

impl IpcRequest {
    /// Extract the optional request correlation ID.
    pub fn request_id(&self) -> Option<&str> {
        match self {
            Self::SetConfig { request_id, .. }
            | Self::ReloadConfig { request_id }
            | Self::TestShortcut { request_id, .. }
            | Self::GetStatus { request_id }
            | Self::StartDaemon { request_id }
            | Self::StopDaemon { request_id } => request_id.as_deref(),
        }
    }
}

// ---------------------------------------------------------------------------
// Message types — Daemon → Client
// ---------------------------------------------------------------------------

/// Responses sent from the daemon to the Tauri GUI client.
///
/// Each response variant corresponds to one or more [`IpcRequest`] variants.
/// `request_id` is echoed from the original request for correlation.

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum IpcResponse {
    /// Current daemon status.
    DaemonStatus {
        running: bool,
        pid: u32,
        version: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        request_id: Option<String>,
    },

    /// Acknowledgment that configuration was loaded with the given bindings.
    ConfigLoaded {
        keys: Vec<KeyBindingJson>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        request_id: Option<String>,
    },

    /// Result of a shortcut test.
    TestResult {
        success: bool,
        message: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        request_id: Option<String>,
    },

    /// A log entry generated by the daemon.
    LogEntry {
        level: String,
        target: String,
        message: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        request_id: Option<String>,
    },

    /// An error occurred.
    Error {
        code: String,
        details: String,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        request_id: Option<String>,
    },
}

impl IpcResponse {
    /// Echo the request_id from the original request into this response.
    ///
    /// This enables the caller to correlate responses with requests.
    pub fn with_request_id(self, request_id: impl Into<Option<String>>) -> Self {
        let rid = request_id.into();
        match self {
            Self::DaemonStatus {
                running,
                pid,
                version,
                ..
            } => Self::DaemonStatus {
                running,
                pid,
                version,
                request_id: rid,
            },
            Self::ConfigLoaded { keys, .. } => Self::ConfigLoaded {
                keys,
                request_id: rid,
            },
            Self::TestResult {
                success, message, ..
            } => Self::TestResult {
                success,
                message,
                request_id: rid,
            },
            Self::LogEntry {
                level,
                target,
                message,
                ..
            } => Self::LogEntry {
                level,
                target,
                message,
                request_id: rid,
            },
            Self::Error { code, details, .. } => Self::Error {
                code,
                details,
                request_id: rid,
            },
        }
    }
}

// ---------------------------------------------------------------------------
// Unified message type (client → server envelope)
// ---------------------------------------------------------------------------

/// A single IPC message that can flow in either direction.
///
/// The `kind` field distinguishes requests from responses; within each
/// kind the inner enum provides further discrimination.
///
/// Supports two JSON formats for backward compatibility:
/// - **Envelope**: `{ "kind": "request", "Request": { "type": "get_status" } }`
/// - **Untagged**: `{ "type": "get_status" }` (shorthand for `Request`)
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum IpcMessage {
    /// A request from the GUI to the daemon.
    Request(IpcRequest),
    /// A response from the daemon to the GUI.
    Response(IpcResponse),
}

impl IpcMessage {
    /// Convert a request into this envelope type.
    pub fn request(req: IpcRequest) -> Self {
        Self::Request(req)
    }

    /// Convert a response into this envelope type.
    pub fn response(resp: IpcResponse) -> Self {
        Self::Response(resp)
    }

    /// Check whether this is a request.
    pub fn is_request(&self) -> bool {
        matches!(self, Self::Request(_))
    }

    /// Check whether this is a response.
    pub fn is_response(&self) -> bool {
        matches!(self, Self::Response(_))
    }

    /// Return the variant kind as a string for logging.
    pub fn kind(&self) -> &'static str {
        match self {
            Self::Request(_) => "request",
            Self::Response(_) => "response",
        }
    }
}

// ---------------------------------------------------------------------------
// JSON-serializable key binding representation
// ---------------------------------------------------------------------------

/// Platform-specific key overrides for IPC serialization.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct PlatformOverridesJson {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub macos: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub windows: Option<Vec<String>>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub linux: Option<Vec<String>>,
}

/// A key binding representation suitable for IPC serialization.
///
/// This is a flattened, JSON-friendly view of [`config::KeyBinding`]
/// used in response messages.

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KeyBindingJson {
    /// Unique identifier for this binding.
    pub id: String,
    /// Key stroke representations (e.g. `["Ctrl+V"]`).
    pub keys: Vec<String>,
    /// The action type (e.g. `"paste"`, `"launch"`, `"system_command"`).
    pub action_type: String,
    /// Platform-specific key overrides (FIX-019).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub overrides: Option<PlatformOverridesJson>,
}

impl From<crate::config::KeyBinding> for KeyBindingJson {
    fn from(binding: crate::config::KeyBinding) -> Self {
        Self {
            id: binding.id,
            keys: binding.keys,
            action_type: binding.action.variant_name(),
            overrides: binding.overrides.map(|o| PlatformOverridesJson {
                macos: o.macos,
                windows: o.windows,
                linux: o.linux,
            }),
        }
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
