//! IPC message types and protocol for GUI ↔ Daemon communication.
//!
//! Provides the [`IpcMessage`] enum that carries all requests from the GUI
//! client to the daemon and all responses back. Messages are serialized
//! as JSON, one per line (newline-delimited frames).
//!
//! The `#[serde(tag = "type")]` attribute enables envelope-style
//! discrimination so the receiver can match responses to requests.

use serde::{Deserialize, Serialize};

// ---------------------------------------------------------------------------
// Message types — Client → Daemon
// ---------------------------------------------------------------------------

/// Requests sent from the Tauri GUI client to the daemon.
///
/// Each variant carries the parameters needed to execute the operation.
///
/// ## Protocol Notes
///
/// - Messages are JSON-encoded with a trailing newline.
/// - The `type` field (enforced by `serde(tag = "type")`) is used to
///   discriminate the variant.
/// - The daemon responds with a matching `IpcMessage` response variant.

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum IpcRequest {
    /// Update daemon configuration.
    SetConfig { config: serde_json::Value },

    /// Ask the daemon to reload configuration from disk.
    ReloadConfig,

    /// Test whether a shortcut can be processed.
    TestShortcut {
        keys: Vec<String>,
        action: serde_json::Value,
    },

    /// Query current daemon status.
    GetStatus,

    /// Start the daemon (if not running).
    StartDaemon,

    /// Stop the daemon (if running).
    StopDaemon,
}

// ---------------------------------------------------------------------------
// Message types — Daemon → Client
// ---------------------------------------------------------------------------

/// Responses sent from the daemon to the Tauri GUI client.
///
/// Each response variant corresponds to one or more [`IpcRequest`] variants.

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum IpcResponse {
    /// Current daemon status.
    DaemonStatus {
        running: bool,
        pid: u32,
        version: String,
    },

    /// Acknowledgment that configuration was loaded with the given bindings.
    ConfigLoaded { keys: Vec<KeyBindingJson> },

    /// Result of a shortcut test.
    TestResult { success: bool, message: String },

    /// A log entry generated by the daemon.
    LogEntry {
        level: String,
        target: String,
        message: String,
    },

    /// An error occurred.
    Error { code: String, details: String },
}

// ---------------------------------------------------------------------------
// Unified message type (client → server envelope)
// ---------------------------------------------------------------------------

/// A single IPC message that can flow in either direction.
///
/// The `kind` field distinguishes requests from responses; within each
/// kind the inner enum provides further discrimination.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum IpcMessage {
    /// A request from the GUI to the daemon.
    Request(IpcRequest),
    /// A response from the daemon to the GUI.
    Response(IpcResponse),
}

impl IpcMessage {
    /// Convert a request into this envelope type.
    pub fn request(req: IpcRequest) -> Self {
        Self::Request(req)
    }

    /// Convert a response into this envelope type.
    pub fn response(resp: IpcResponse) -> Self {
        Self::Response(resp)
    }

    /// Check whether this is a request.
    pub fn is_request(&self) -> bool {
        matches!(self, Self::Request(_))
    }

    /// Check whether this is a response.
    pub fn is_response(&self) -> bool {
        matches!(self, Self::Response(_))
    }

    /// Return the variant kind as a string for logging.
    pub fn kind(&self) -> &'static str {
        match self {
            Self::Request(_) => "request",
            Self::Response(_) => "response",
        }
    }
}

// ---------------------------------------------------------------------------
// JSON-serializable key binding representation
// ---------------------------------------------------------------------------

/// A key binding representation suitable for IPC serialization.
///
/// This is a flattened, JSON-friendly view of [`config::KeyBinding`]
/// used in response messages.

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct KeyBindingJson {
    /// Unique identifier for this binding.
    pub id: String,
    /// Key stroke representations (e.g. `["Ctrl+V"]`).
    pub keys: Vec<String>,
    /// The action type (e.g. `"paste"`, `"launch"`, `"system_command"`).
    pub action_type: String,
}

impl From<crate::config::KeyBinding> for KeyBindingJson {
    fn from(binding: crate::config::KeyBinding) -> Self {
        Self {
            id: binding.id,
            keys: binding.keys,
            action_type: binding.action.variant_name(),
        }
    }
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

impl crate::actions::Action {
    /// Return a short string identifying the action variant.
    fn variant_name(&self) -> String {
        match self {
            Self::Paste { .. } => "paste".to_string(),
            Self::Launch { .. } => "launch".to_string(),
            Self::Remap { .. } => "remap".to_string(),
            Self::Shortcut { .. } => "shortcut".to_string(),
            Self::SystemCommand { .. } => "system_command".to_string(),
            Self::TextInsert { .. } => "text_insert".to_string(),
        }
    }
}
